import Head from 'next/head'
import React from 'react'
import Header from '../components/Header/Header'

import { requestGames, requestMovies } from '../api/moviesAndGames'
import { IItem } from '../interfaces'
import { GetStaticProps } from 'next'
import RenderList from '../components/RenderList'

export const getStaticProps: GetStaticProps = async () => {
  const { message: movies } = await requestMovies()
  const { message: games } = await requestGames()

  return {
    props: {
      movies,
      games,
    }
  }
}

const Dashboard = (props: { movies: IItem[], games: IItem[] }) => {
 const { movies, games } = props
  
  return (
    <>
      <Head>
        <title>Rent a Movie - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Header />
        <RenderList movies={movies} games={games} />
      </>
    </>
  )
}

export default Dashboard
